[build]
  base = ""
  publish = "public"
  command = "npm build"

  [build.environment]
    REACT_APP_BASE_API_URL=""
    REACT_APP_SECRET_KEY="Its a see key ret"

[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
